---

- hosts: vm2
  become: true
  become_user: root
  tasks:
  - name: install git
    package:
      name:
        - git
      state: latest

  - name: install apache2 and php support lib package
    package: 
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: host
  connection: local
  tasks:
  - name: install nginx
    package:
      name:
        - nginx
