---
- name: Play for VM1
  hosts: VM1
  become: yes

  tasks:
   - name: Install Nginx
     become: true 
     apt: 
       name: nginx
       state: absent
       autoremove: yes

- name: Play for VM2
  hosts: VM2
  become: yes
  tasks:
   - name: Install Apache
     become: true 
     apt: 
       name: apache2
       state: absent
       autoremove: yes

- name: Play for both VMs
  hosts: Oba
  become: yes
  tasks:
   - name: Install Apache Benchmark
     become: true 
     apt: 
       name: apache2-utils
       state: absent
       autoremove: yes
